### ISSUE TITLE
Improvement needed...

### ISSUE THREAD

**Issue by XanuduBuster** [theavian/theavian#1]
In the section where it says `"I have experience"` just don't lie that you know lots and lots of `programing languages`... like many people have experience and USE `android`, but you pretend that `android` is a `programing language`, also in `pronounces` its very wrong `pronounces` means `he/him` or `she/her` or `they/them`, not like `genius`, and `other etc, etc...` also `"I have experience with"` is stating that which `programing language` experience you have not like `software's` like sure `bash` is sort of a `programing language` but not `android`... Please improve your profile `README.md`

**Comment by theavian** [comment]
Okay
